// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5WRVcMIdfwhRjcJJLWWs0-XEf67oH1EA',
    appId: '1:513384264398:web:6b081816c024380427169f',
    messagingSenderId: '513384264398',
    projectId: 'coding-minds-bootstrap-7698e',
    authDomain: 'coding-minds-bootstrap-7698e.firebaseapp.com',
    storageBucket: 'coding-minds-bootstrap-7698e.appspot.com',
    measurementId: 'G-ZL2E8VQJQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZuYw9io-O2kBiZEkYeyesvJsSzyCeCM',
    appId: '1:513384264398:android:dd83883d1191772b27169f',
    messagingSenderId: '513384264398',
    projectId: 'coding-minds-bootstrap-7698e',
    storageBucket: 'coding-minds-bootstrap-7698e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNXmOjO0_f7wzGacYnMl2LfwFpYas5DA',
    appId: '1:513384264398:ios:5b3d9583aa20e6dc27169f',
    messagingSenderId: '513384264398',
    projectId: 'coding-minds-bootstrap-7698e',
    storageBucket: 'coding-minds-bootstrap-7698e.appspot.com',
    iosBundleId: 'com.example.codingMindsBootstrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNXmOjO0_f7wzGacYnMl2LfwFpYas5DA',
    appId: '1:513384264398:ios:5b3d9583aa20e6dc27169f',
    messagingSenderId: '513384264398',
    projectId: 'coding-minds-bootstrap-7698e',
    storageBucket: 'coding-minds-bootstrap-7698e.appspot.com',
    iosBundleId: 'com.example.codingMindsBootstrap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5WRVcMIdfwhRjcJJLWWs0-XEf67oH1EA',
    appId: '1:513384264398:web:affefd8db1b84f2027169f',
    messagingSenderId: '513384264398',
    projectId: 'coding-minds-bootstrap-7698e',
    authDomain: 'coding-minds-bootstrap-7698e.firebaseapp.com',
    storageBucket: 'coding-minds-bootstrap-7698e.appspot.com',
    measurementId: 'G-PFR2RPPL8B',
  );

}